### ISSUE TITLE
Use portable-atomic, please?

### ISSUE THREAD

**Issue by he32** [yashs662/rust_kanban#13]
**Is your feature request related to a problem? Please describe.**
This package will not build on systems with CPUs which lack native 64-bit atomic support, such as 32-bit powerpc.  The build ends with

```
   Compiling rust-kanban v0.8.2 (/usr/pkgsrc/misc/rust-kanban/work/rust_kanban-0.8.2)
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> src/ui/text_box.rs:17:20
   |
17 |     sync::atomic::{AtomicU64, Ordering},
   |                    ^^^^^^^^^
   |                    |
   |                    no `AtomicU64` in `sync::atomic`
   |                    help: a similar name exists in the module: `AtomicU32`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rust-kanban` (lib) due to previous error
```

**Describe the solution you'd like**
The `portable-atomic` provides replacement functionality if you need to insist on 64-bit atomic operations.

**Describe alternatives you've considered**
As far as I know there is no other known solution to this issue.

**Comment by yashs662** [comment]
I will look into this, thanks for reporting!

**Comment by yashs662** [comment]
Please check if the new branch has fixed your issue, this change doesn't affect anything for regular builds at least according to the Windows, Linux, and mac-os actions, if it works for your specific configuration. I'll merge it!

**Comment by he32** [comment]
Thanks! Applying that as a patch makes the package now build on NetBSD/macppc 10.0 with rust 1.78.0.
